#!/usr/bin/env node
/**
 * Run once before using the client: node scripts/setup.js
 * Prompts for credentials and writes scripts/config.js.
 * Re-run at any time to update — existing values shown as defaults.
 */

import readline from 'readline'
import { writeFileSync, existsSync, readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const CONFIG_PATH = join(__dirname, 'config.js')

const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
const ask = (q) => new Promise(resolve => rl.question(q, resolve))

let existing = { BEARER_TOKEN: '', DEFAULT_LIST_ID: '' }
if (existsSync(CONFIG_PATH)) {
  try {
    const src = readFileSync(CONFIG_PATH, 'utf8')
    const match = (key) => (src.match(new RegExp(`${key}:\\s*'([^']*)'`)) || [])[1] || ''
    existing.BEARER_TOKEN    = match('BEARER_TOKEN')
    existing.DEFAULT_LIST_ID = match('DEFAULT_LIST_ID')
  } catch {}
}

console.log('\n── X List Reader setup ──────────────────────────────────')
console.log('Get your Bearer Token at https://console.x.com')
console.log('Press Enter to keep an existing value.\n')

const token  = (await ask(`Bearer Token${existing.BEARER_TOKEN ? ' [current hidden]' : ''}: `)).trim()
             || existing.BEARER_TOKEN
const listId = (await ask(`Default List ID${existing.DEFAULT_LIST_ID ? ` [${existing.DEFAULT_LIST_ID}]` : ' (optional)'}: `)).trim()
             || existing.DEFAULT_LIST_ID

rl.close()

if (!token) {
  console.error('\nError: Bearer Token is required.')
  process.exit(1)
}

writeFileSync(CONFIG_PATH, `// Auto-generated by setup.js — do not commit this file
export const config = {
  BEARER_TOKEN:    '${token}',
  DEFAULT_LIST_ID: '${listId}',
}
`, 'utf8')

console.log('\n✓ Config written to scripts/config.js')
console.log('  Import the client with: import { fetchListTweets } from \'./scripts/client.js\'\n')